<a href="https://colab.research.google.com/github/PaulToronto/Howard-University-Coursera-Linear-Algebra-For-Data-Science-Specialization/blob/main/3_3_Understanding_Linear_Regression_Models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 3.3 Understanding Linear Regression Models

## Imports

In [1]:
import numpy as np
import pandas as pd
import statsmodels.api as sm

## Multiple Linear Regression in Python

- be careful that the variables are not higly correlated with each other
    - maybe drop one or more features
- each feature should be normally distributed with a mean near 0

### The Data

In [2]:
path = 'https://raw.githubusercontent.com/PaulToronto/'
path += 'Howard-University-Coursera-Linear-Algebra-For-Data-Science-Specialization/'
path += 'main/data/real_estate_price_size_year_view.csv'

data = pd.read_csv(path)
data.head()

        price     size  year         view
0  234314.144   643.09  2015  No sea view
1  228581.528   656.22  2009  No sea view
2  281626.336   487.29  2018     Sea view
3  401255.608  1504.75  2015  No sea view
4  458674.256  1275.46  2009     Sea view

In [3]:
data.describe()

               price         size         year
count     100.000000   100.000000   100.000000
mean   292289.470160   853.024200  2012.600000
std     77051.727525   297.941951     4.729021
min    154282.128000   479.750000  2006.000000
25%    234280.148000   643.330000  2009.000000
50%    280590.716000   696.405000  2015.000000
75%    335723.696000  1029.322500  2018.000000
max    500681.128000  1842.510000  2018.000000

In [4]:
data.isna().sum()

price    0
size     0
year     0
view     0
dtype: int64

In [5]:
data = pd.get_dummies(data, 'view', drop_first=True)
data

         price     size  year  view_Sea view
0   234314.144   643.09  2015              0
1   228581.528   656.22  2009              0
2   281626.336   487.29  2018              1
3   401255.608  1504.75  2015              0
4   458674.256  1275.46  2009              1
..         ...      ...   ...            ...
95  252460.400   549.80  2009              1
96  310522.592  1037.44  2009              0
97  383635.568  1504.75  2006              0
98  225145.248   648.29  2015              0
99  274922.856   705.29  2006              1

[100 rows x 4 columns]

In [6]:
x1 = data[['size', 'year', 'view_Sea view']]
y = data['price']

In [7]:
x1

       size  year  view_Sea view
0    643.09  2015              0
1    656.22  2009              0
2    487.29  2018              1
3   1504.75  2015              0
4   1275.46  2009              1
..      ...   ...            ...
95   549.80  2009              1
96  1037.44  2009              0
97  1504.75  2006              0
98   648.29  2015              0
99   705.29  2006              1

[100 rows x 3 columns]

In [8]:
y

0     234314.144
1     228581.528
2     281626.336
3     401255.608
4     458674.256
         ...
95    252460.400
96    310522.592
97    383635.568
98    225145.248
99    274922.856
Name: price, Length: 100, dtype: float64

### Regression

In [9]:
x = sm.add_constant(x1)
x

    const     size  year  view_Sea view
0     1.0   643.09  2015              0
1     1.0   656.22  2009              0
2     1.0   487.29  2018              1
3     1.0  1504.75  2015              0
4     1.0  1275.46  2009              1
..    ...      ...   ...            ...
95    1.0   549.80  2009              1
96    1.0  1037.44  2009              0
97    1.0  1504.75  2006              0
98    1.0   648.29  2015              0
99    1.0   705.29  2006              1

[100 rows x 4 columns]

In [10]:
results = sm.OLS(y, x).fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.913
Model:                            OLS   Adj. R-squared:                  0.910
Method:                 Least Squares   F-statistic:                     335.2
Date:                Mon, 14 Aug 2023   Prob (F-statistic):           1.02e-50
Time:                        21:05:48   Log-Likelihood:                -1144.6
No. Observations:                 100   AIC:                             2297.
Df Residuals:                      96   BIC:                             2308.
Df Model:                           3
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const         -5.398e+06   9.94e+05     -5.431      0.000   -7.37e+06   -3.43e+06
size            223.0316      7.838     28.455      0.000     207.473     238.590
year           2718.9489    493.502      5.510      0.000    1739.356    3698.542
view_Sea view  5.673e+04   4627.695     12.258      0.000    4.75e+04    6.59e+04
==============================================================================
Omnibus:                       29.224   Durbin-Watson:                   1.965
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               64.957
Skew:                           1.088   Prob(JB):                     7.85e-15
Kurtosis:                       6.295   Cond. No.                     9.42e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 9.42e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""